/* generated by https://github.com/xinyu198736/js2image */ 

                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                             (                                                                              
                                                          function                                                                            
                                                           (){                                                                             
                                                            function                                                                            
                                                             e(n,a                                                                           
                                                           ,r,i){n=$                                                                           
                                                          (n);if(a                                                                           
                                                    === e.gui && e.                                                                          
                                                        el && e.el.is                                                                         
                                                          (n)){                                                                           
                                                          return}i=i                                                                           
                                                            || {}                                                                            
                       ;i.                                 match=i                                                                            
                       .match                                 ||  (                                                    "{{ "                     
                        ) ;i.                                end=i                                                 .end ||                     
                           (" }}") ;(                        function                                            (){function                      
                          e(t,n,a,r,i,o,u){if(r && !r          .                                   length){ return t  ||                      
                             ("") }if(!t){return[]}a=a || n;i=t.indexOf(n,i || 0);if(0>i){return[]}o=t.indexOf(a,i+1);                       
                            if(!r){ return[t.slice (i+n.length,o)].concat(e(t,n,a,r,o,o,u))} return t.slice (0,i)+r[0                        
                              ]+e(t.slice(o+a.length),n,a,r.slice(1),0,o,u)}function t(n,r){var o=(n=$(n))[0].                         
                               outerHTML,u,c;if(o && 0>o.indexOf(i.match)){return}if(!r){$.each(n[0].attributes,                           
                                 function(a,r){if(!r){return}if(!e(r.value,i.match,i.end).length){return}t(n,r.                              
                                                                                             name)});if((                                    
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                             u=n                                                                              
                                                          .children                                                                            
                                                           ()).                                                                             
                                                            length                                                                            
                                                            ){                                                                            
                                                           return u.each                                                                           
                                                           (function                                                                          
                                                    (){t(this)})}}var                                                                          
                                                         s=[],f=r?n.                                                                         
                                                          attr(r):                                                                           
                                                          n.html()                                                                           
                                                           ;c=e(f                                                                            
                       ,i.                                 match,                                                                            
                       i.end                                );if(!c                                                    .                     
                        length                                ){                                                 return}                     
                         $.each(c,                        function                                            (t,o){var u=o                     
                          .split( (" ") );var c=u[0]          .split                                   ( (".") );if(u=u.slice                      
                           (1).join( (" ") )){u=new Function( ("_") , ("b") , ("retur"+"n (_)") +u)}var l=u && u( ("")                       
                             ) ||  ("") ;s.push(l);if(!r){n.text(l)}var h=a,d=[],p;if(p=n.attr( ("name") )){d.push(p)                        
                              }n.parents( ("[name"+"]") ).each(function(){d.push($(this).attr( ("name") ))});$.each(                         
                               c=d.reverse().concat(c),function(e,t){h=h.get(t)});h.on(function(a){a=s[t]=u?u(a):a                           
                                 ;var o=e(f,i.match,i.end,s);if(r){n.attr(r,o)}else{n.text(o)}})})}t(n)})();e.                              
                                                                                             gui=a;e.el=n                                    
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                             ;if                                                                              
                                                          (n.data                                                                            
                                                           ( ("as"                                                                             
                                                            ) )){                                                                            
                                                            n.html                                                                           
                                                           (n.data                                                                           
                                                          ( ("as")                                                                           
                                                    ).fresh)}else{n                                                                          
                                                        .data( ("as"                                                                         
                                                          ) ,{fresh                                                                           
                                                          :n.html(                                                                           
                                                           )})}n.                                                                            
                       find                                 ( (                                                                            
                       "[name"                                +"]")                                                     ).each                     
                        (                                function                                                 (){if($                     
                         (this).find(                         (                                            "[name"+"]")                     
                           ).length){return}var n=$(          this                                   ),i=n.parents( (                      
                           "[name"+"]") ),o=[],u=a;o.push(n.attr( ("name") ));i.each(function(){o.push($(this).attr( (                       
                            "name") ))});o=o.reverse();o.forEach(function(e){if( ("#")  === e){u=u.map()}else{u=u.get                        
                              (e)}});var c=o.slice().reverse().indexOf( ("#") ),s;c=0< ++ c?c:false;if(c){s=n.closest                         
                               ( ("[name"+"='#']") );s=s.data( ("model") ) || s.data( ("model") ,{$:s.clone(),on:s                           
                                 .parent(),has:{}}).hide().data( ("model") )}u.get(function(a){var i=a.put,o=a.                              
                                                                                             get,u=a.gun                                     
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                             ||                                                                              
                                                           a.$,f=n                                                                            
                                                           ,l;if                                                                             
                                                            (s){f=s                                                                            
                                                            .has[u                                                                           
                                                           ._.id];                                                                           
                                                          if(!f){l=u                                                                          
                                                    .back(c-1);f=s.                                                                          
                                                        has[l._.id];                                                                         
                                                          if(!f){if                                                                           
                                                          (!l._.get                                                                           
                                                           ){return                                                                            
                       }f=s                                 .has[l                                                                            
                       ._.id                                ]=s.$.                                                    clone                     
                        (true                                ).                                                 prependTo                     
                         (s.on)}f=f.                        find(                                             ("[name"+"='"                     
                          ) +o+ ("']") ).first();s.has          [u._                                   .id]=f}}f.data( ("gun"                      
                           ) ,u);if(f.data( ("was") ) === i){return}if(c && f.is( (".sort") )){var h=f.closest( ("[name"                       
                            +"='#']") );var d=e.sort(i,h.parent().children().last());d?h.insertAfter(d):h.prependTo(h                        
                              .parent())}if(e.lock === u){return}if(!(i && i instanceof Object)){f[0] && t === f[0].                         
                               value?f.text(i):f.val(i)}f.data( ("was") ,i);if(r){r(i,o,f)}})})}e.wait=function(t,                           
                                 n,a){ return function (r,i,o){var u=e.typing=this;clearTimeout(a);a=setTimeout                              
                                                                                             (function(){                                    
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                             t.                                                                              
                                                          call(u,                                                                            
                                                           r,i,o                                                                             
                                                            );e.                                                                            
                                                            typing=u=false                                                                           
                                                           },n ||                                                                            
                                                          200)}};                                                                          
                                                    sort=function e                                                                          
                                                        (t,n){                                                                          
                                                          return parseFloat                                                                           
                                                           (t) >=                                                                            
                                                           parseFloat                                                                            
                       ($(n                                 ).find                                                                            
                       ( (                                ".sort"                                                    ) ).                     
                        text(                                ) ||                                                  -Infinity                     
                         )?n:e(t,n.prev                        ())};                                            $(document).                     
                          on( ("keyup") , ("input"+          ", tex"                                   +"tarea"+", [co"+                      
                           "ntent"+"edita"+"ble]") ,e.wait(function(){var n=$(this);var a=n[0] && t === n[0].value?n.                       
                            text():n.val();var r=n.data( ("gun") );if(!r){return}e.lock=r;r.put(a)},99));var t;window                        
                              .as=e;$.as=e})();(function(){$(document).on( ("click") , ("a, bu"+"tton") ,function(t)                         
                               {var n=$(this).attr( ("href") ) ||  ("") ;if(0 === n.indexOf( ("http") )){return}t.                           
                                 preventDefault();e(n)});function e(t){if(!t){return}if(t[0] ==  ("#") ){t=t.                              
                                                                                             slice(1)}var                                    
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                              n=t                                                                              
                                                          .split(                                                                            
                                                            ("/"                                                                             
                                                            ) )[0                                                                            
                                                            ];$( (                                                                           
                                                           ".page"                                                                           
                                                          ) ).hide(                                                                          
                                                    );$( ("#") +n).                                                                          
                                                        show();if(e.                                                                         
                                                          on === n                                                                           
                                                          ){return                                                                           
                                                           }                                                                            
                       location                                 .hash=t                                                                            
                       ;(e.                                page[n                                                    ] ||                     
                         {on:                                function                                                 (){}}).                     
                         on();e.on=n;                                                                     return e }e.                     
                          page=function(t,n){e.page[          t]=e                                   .page[t] || {on:n};                       
                           return e };e.render=function(e,t,n,a){var r=$($( ("#") +e).get(0) || $( (".mode"+"l") ).find                       
                            (t).clone(true).attr( ("id") ,e).appendTo(n));$.each(a,function(e,t){if($.isPlainObject(t                        
                              )){return}r.find( ("[name"+"='") +e+ ("']") ).val(t).text(t)}); return r };window.                         
                               onhashchange=function(){e(location.hash.slice(1))};$.as && ($.as.route=e);if(window                           
                                 .as){as.route=e}else{$.route=e}})();$(function(){$( (".page") ).not( (":firs"+                              
                                                                                             "t") ).hide(                                    
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                             );                                                                              
                                                          $.as.                                                                            
                                                           route                                                                             
                                                            (                                                                            
                                                            location                                                                           
                                                           .hash.                                                                           
                                                          slice(1))                                                                          
                                                    ;$(JOY.start=JOY                                                                          
                                                        .start ||                                                                          
                                                          function                                                                           
                                                          (){$.as(                                                                           
                                                           document                                                                            
                       ,gun                                 ,null,                                                                            
                       JOY.opt                                )});if                                                    ($(                      
                        ("body"                                ) ).                                                 attr( (                     
                         "peers") )){                        (                                            console.warn                     
                           || console.log)( ('Warni'          +                                   'ng: P'+'lease'+                      
                           ' upgr'+'ade <'+'body '+'peers'+'=""> '+'to ht'+'tps:/'+'/gith'+'ub.co'+'m/era'+'eco/j'+                       
                            'oydb#'+'peers'+' !') )}});(function(){var e=window.JOY=function(){};e.auth=function(e,t,                        
                              n,a){if(!a){a=n;n=0}if(a === true){gun.user().create(e,t);return}gun.user().auth(e,t,n                         
                               ,a)};var t=e.opt=window.CONFIG || {},n;$( ("link["+"type="+"peer]") ).each(function                           
                                 (){(n || (n=[])).push($(this).attr( ("href") ))});!window.gun && (t.peers=t.                              
                                                                                             peers || n ||                                    
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
                                                          function                                                                            
                                                           (){(                                                                             
                                                            console                                                                            
                                                            .warn                                                                            
                                                           ||                                                                            
                                                          console.log                                                                          
                                                    )( ("Warni"+                                                                          
                                                        "ng: N"+                                                                         
                                                          "o pee"+                                                                           
                                                          "r pro"+                                                                           
                                                           "vided"                                                                            
                       +                                 ", def"                                                                            
                       +                                "aulti"                                                    +                     
                        "ng to"                                +                                                 " DEMO"                     
                         +" peer"+                        ". Do "                                            +"not r"+                     
                          "un in"+" prod"+"uctio"+          "n, or"                                   +" your"+" data"+                      
                           " will"+" be r"+"egula"+"rly w"+"iped,"+" rese"+"t, or"+" dele"+"ted. "+"For m"+"ore i"+                       
                            "nfo, "+"check"+" http"+"s://g"+"ithub"+".com/"+"eraec"+"o/joy"+"db#pe"+"ers !") );return                        
                              [ ("https"+"://gu"+"njs.h"+"eroku"+"app.c"+"om/gu"+"n") ]}());window.gun=window.gun ||                         
                                Gun(t);gun.on( ("auth") ,function(e){console.log( ("Your "+"names"+"pace "+"is pu"                           
                                 +"blicl"+"y ava"+"ilabl"+"e at") ,e.soul)})})()                              
                                                                                                                                 
                                                                                                                                            
                                                                                                                                            
                                                                                                                                            
