/* generated by my mom */ 

                              (                             function                                       
                            (){var                       t;if(                                        
                            typeof                 window !==                                          
                               ("undef"        +"ined") ){                                            
t=window                             }if(typeof global !==  (                                              
"undef"                          +"ined") ){t=global}t=t                                                
  || {};var                  e=t.console || {log:                                                  
 function(){}};function r(t,e){ return e ?require(                                                   
  t):t.slice?r[n(t)]:function(e,i){t(e={exports:                                                     
  {}});r[n(i)]=e.exports};function n(t){                                                       
   return t.split ( ("/") ).slice(-1).toString(                                                      
    ).replace( (".js") , ("") )}}if(typeof module                                                     
     !==  ("undef"+"ined") ){var n=module}r(function                                                   
     (t){if(typeof window !==  ("undef"+    "ined")                                                  
       ){t.window=window}var e=t.window        || t;var                                                 
         r=e.AXE || function(){};if(r.          window=t                                               
         .window){r.window.AXE=r}try{            if(typeof                                              
           n !==  ("undef"+"ined") )              {n.                                            
            exports=r}}catch(t){}t.                exports=r                                           
             })(r, ("./roo"+"t") );                  r(function                                         
               (t){var n=r( ("./roo"                    +"t") )                                        
                 ,i=(n.window || {}                     ).Gun ||                                       
                    r( ("./gun") ,1                       );(i.                                     
                     AXE=n).GUN=n.                        Gun=i;i                                    
                        .on( ("opt"                         ) ,                                  
                           function                           (t){u(t                                 
                              );this                            .to.next                               
                                                                (t)});                              
                                                                 function                             
                                                                    u(t){if                           
                                                                    (t.axe)                          
                                                                     {return}                        
                                                                       var n=t                       
                                                                        .opt,u=n                     
                                                                          .peers;                    
                                                                           if(false                   
                                                                              === n.                 
                                                                              axe){                
                                                                               return}if              
                                                                                 (typeof             
                                                                                   process           
                                                                                     !==  (          
                                                                                     "undef"         
                                                                                       +"ined"       
                                                                                        )  &&        
                                                                                         ("false"    
                                                                                           )  ===    
                                                                                             ("") +( 
                                                                                              process
                                                                                               .env  
                               ||                              {                                       
                            }).AXE                      ){return                                        
                            }var o=t                .axe={},f                                          
                             ;var s=n        .mesh=n.mesh                                             
||                              i.Mesh(t);e.log( ("AXE e"                                              
+"nable"                          +"d.") );function p(t,                                                
 e){var                  r=Object.keys(e.put);var                                                  
  o=r[0];var f=t(o);if(!f){return}var a=[];i.obj.map                                                   
  (f.split( (",") ),function(t){if(t in u){a.push                                                     
  (t);s.say(e,u[t])}});if(n.super){t(o,a.join(                                                       
   (",") ))}}function c(t){var e;if(!t){return}                                                      
    if( ("strin"+"g") !=typeof(e=t[ ("#") ])){                                                     
    return} return e }var d=(i.window || {}).Radix                                                   
      || r( ("./lib"+"/radi"+"x") ,1);t.opt    .dht=d(                                                  
      );t.on( ("in") ,function e(r){var        u=this                                                 
        .to,f=(r._ || {}).via;var a=n.          dht;var                                               
          s=o.routes || (o.routes={})            ;var p=r                                              
          .get,d,v;if(p && n.super &&               f && (v=c                                            
            (p))){d=v;(s[d] || (s[d]                ={}))[f                                           
             .id]=f;(f.routes || (f                  .routes=                                         
               {}))[d]=s[d]}if((v=r                    [ ("@")                                        
                  ]) && (v=t.dup.s[                     v]) &&                                        
                   (v=v.it)){(v=v._                        || ok)                                     
                     .ack=(v.ack ||                         0)+1}u                                    
                        .next(r);if                         (n.rtc &&                                  
                            r.dht){                           i.obj.map                                 
                              (r.dht                            ,function                               
                                                                (t,e){a                              
                                                                 (e,t);i                             
                                                                   .obj.map                           
                                                                    (t.split                          
                                                                     ( (",")                         
                                                                       ),                       
                                                                        function                     
                                                                          (t){if(                    
                                                                           !t || t                   
                                                                              in n.                 
                                                                              peers ||                
                                                                                t === n              
                                                                                 .pid ||             
                                                                                   n.           
                                                                                    announce          
                                                                                     [t]){         
                                                                                       return}       
                                                                                        n.      
                                                                                         announce    
                                                                                           [t]=true   
                                                                                            ;n. 
                                                                                              announce
                                                                                               (t)}  
                              )}                             )}                                       
                            });s.                      hear[                                         
                            ("opt")                 ]=function                                          
                             (e,r){if        (e.ok){                                             
return n.log                              (e)}var f=e.opt;if(!f){                                              
return                          }f=f.peers;if(!f || !i                                                
 .text.is(f                 )){return}if(o.up[f] ||                                                   
 6 <= Object.keys(o.up).length){return}var a=f;t.$                                                   
  .opt(a);a=u[f];if(!a){return}a.retry=9;s.wire(                                                     
  a);if(r){s.say({dam: ("opt") ,ok:1, "@" :e[ (                                                      
   "#") ]},r)}};setInterval(function(e){if(!(e=t                                                      
    .stats && t.stats.stay)){return}(e.axe=e.axe                                                     
     || {}).up=Object.keys(o.up || {})},1e3*60);                                                   
     setTimeout(function(e){if(!(e=t.stats     && t.                                                  
      stats.stay)){return}i.obj.map((e.       axe ||                                                  
        {}).up,function(t){s.hear.opt(          {opt:{                                               
         peers:t}})})},1e3);if(t.opt.            super){                                              
          var v=0;s.way=function(t){              if(t.rtc                                            
            ){if(t.rtc.to){var e=d?d                [t.rtc.                                           
             to]:null;if(e){s.say(t                  ,e)}return                                         
               }}if(t.get){s.say(t,                    o.up)}if                                        
                 (t.get && (f=c(t.get                     ))){var                                       
                    r=f;var u=o.                       routes                                      
                     || (o.routes={                        });var                                     
                        d=u[r];                         function                                  
                            v(e,r){                           if(!e){                                 
                                                           return v                               
                                                                 (n.peers                              
                                                                 )}var                              
                                                                   i=Object                           
                                                                    .keys(e                          
                                                                     );var u=t                        
                                                                       ._ || a                       
                                                                        ;                     
                                                                          clearTimeout                    
                                                                           (u.lack                   
                                                                             );var f                 
                                                                              ,p,c=1;                
                                                                               while((f=i              
                                                                                 [u.turn             
                                                                                   || 0])            
                                                                                    &&  c--          
                                                                                      ){p=e[         
                                                                                       f];u.       
                                                                                        turn=(u      
                                                                                         .turn ||    
                                                                                            0)+1;if   
                                                                                            (r && r[ 
                                                                                              f] || 
                                                                                               false  
                               ===                              s                                       
                            .say(t                      ,p)){                                         
                            ++ c}}if                (0<c){if(                                          
                             e === n.        peers){return                                            
}                              return u.turn =0,v(n.peers                                              
,e)}var                           d=t[ ("##") ],l=u.ack                                                
 ;u.                 lack=setTimeout(function                                                  
 (){if(l && d && d === t[ ("##") ]){return}if(u.turn                                                   
   >= (o.turns || 3)){return}v(e,r)},25)} return v                                                     
   (d)}if(t.put){var u=o.routes || (o.routes={}                                                      
   );var d={};i.obj.map(t.put,function(t,e){var                                                      
     r=e;var n=u[r];if(!n){return}i.obj.to(n,d)}                                                     
    );s.say(t,d);return}s.say(t,n.peers);return;if                                                   
     (!t.put){s.say(t);return}p(n.dht,t)}    }else{s                                                  
      .route=function(t){if(t.rtc){}if(       !t.put)                                                 
        {s.say(t);return}p(n.dht,t);i.          obj.map                                               
         (u,function(e){if(e.url){s.say            (t,e)}}                                              
          )}}o.up={};t.on( ("hi") ,              function                                            
            (t){this.to.next(t);if(!t                .url){                                           
             return}o.up[t.id]=t});                  t.on( (                                         
               "bye") ,function(t){                    this.to                                        
                 .next(t);if(t.url)                     {delete                                       
                    o.up[t.id]}i.obj                       .map(t.                                     
                     routes,function                        (e,r){                                    
                        delete e[t.                         id];if(i                                  
                           .obj.empty                           (e)){                                 
                              delete                             o.routes                               
                                                                [r]}})}                              
                                                                 )}                             
                                                                   function                           
                                                                     o(t,e,                          
                                                                     r){if(!r                        
                                                                        || !e                        
                                                                        || !t){                     
                                                                          return}                    
                                                                           var n=t                   
                                                                             (e);var                 
                                                                               u=n?n.                
                                                                               split( (              
                                                                                 ",") ):             
                                                                                  [];i.obj           
                                                                                    .map(r.          
                                                                                     split(          
                                                                                       (",") )       
                                                                                        ,function      
                                                                                         (t){if(t    
                                                                                            && u.   
                                                                                            indexOf( 
                                                                                              t) === 
                                                                                               -1){  
                              u.                             push                                       
                            (t)}})                      ;u=u.                                        
                            join( (                ",") );t(                                          
                             e,u);         return u }var                                            
 f=                             {},a=true,s;t.exports=n}                                              
)(r, (                          "./axe") )})()                                                
                                                                    
                                                    
                                                       
                                                        
                                                         
                                                         
                                                       
                                                           
                                                              
                                                                 
                                                                   
                                                                    
                                                                       
                                                                        
                                                                           
                                                                             
                                                                               
                                                                                 
                                                                                   
                                                                                       
                                                                                         
                                                                                              
                                                                                              
                                                                                              
                                                                                              
                                                                                             
                                                                                              
                                                                                             
                                                                                              
                                                                                              
                                                                                              
                                                                                              
                                                                                             
                                                                                              
                                                                                             
                                                                                              
                                                                                              
                                                                                              
                                                                                              
                                                                                             
                                                                                              
                                                                                             
                                                                                              
                                                                                                 
